name       : python-parsimonious
version    : 0.7.0
release    : 1
source     :
    - https://pypi.python.org/packages/11/db/06a1d0a41b4d236cd84fb27fced4479645b1fb6100501e03accde2804e51/parsimonious-0.7.0.tar.gz : 396d424f64f834f9463e81ba79a331661507a21f1ed7b644f7f6a744006fd938
license    : MIT
component  : programmign.python
summary    : Parsimonious aims to be the fastest arbitrary-lookahead parser written in pure Python
description: |
    Parsimonious aims to be the fastest arbitrary-lookahead parser written in pure Python
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
    - python-six
rundeps    :
    - python-six
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
